title: hansanhha
description: Internet Notebook
url: https://hansanhha.github.io

plugins:
  # - jekyll-feed
  # - jekyll-sitemap
  - jekyll-seo-tag

collections:
  projects:
    output: true 

  code:
    output: true

  daily:
    output: true

  archives:
    output: true
  
  sunrise:
    output: true