server:
  port: 8083

spring:
  application:
    name: payment-service

logging:
  level:
    io.opentelemetry.exporter.logging: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces